version: "3"
services:
  app-demo:
    image: demo:latest
    ports:
      - "8080:8080"
    networks:
      - app-db
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.8
    networks:
      - app-db
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic 
      - MYSQL_DATABASE=petclinic   

networks:
  app-db: 
